# Generated by Django 2.2.5 on 2019-09-29 08:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WikiPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_index', models.IntegerField()),
                ('title', models.CharField(max_length=64)),
                ('content', models.TextField(max_length=2500)),
                ('created_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('edited_datetime', models.DateTimeField(null=True)),
            ],
        ),
    ]
