# Generated by Django 2.2.5 on 2019-09-29 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wikipage',
            name='edited_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
