# Generated by Django 2.2.5 on 2019-09-29 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0002_auto_20190929_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='wikipage',
            name='url',
            field=models.CharField(default='beep', max_length=64),
            preserve_default=False,
        ),
    ]
