# Generated by Django 2.2.5 on 2019-09-29 10:32

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0003_wikipage_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wikipage',
            name='content',
            field=tinymce.models.HTMLField(verbose_name='Content'),
        ),
    ]
