# Generated by Django 2.2.5 on 2019-10-20 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0007_auto_20191016_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wikipage',
            name='display_index',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='wikipage',
            name='title',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='wikipage',
            name='url',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
