# Generated by Django 2.2.5 on 2019-09-28 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(max_length=250),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='description',
            field=models.TextField(max_length=250),
        ),
    ]
