# Generated by Django 2.2.5 on 2019-09-28 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_auto_20190928_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='subcategories',
            field=models.ManyToManyField(default=None, to='forum.Subcategory'),
        ),
    ]
