# Generated by Django 2.2.5 on 2019-09-28 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_auto_20190928_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='subcategories',
            field=models.ManyToManyField(blank=True, to='forum.Subcategory'),
        ),
    ]
