# Generated by Django 2.2.5 on 2019-10-09 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0007_auto_20191009_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='date_edited',
            field=models.DateTimeField(null=True),
        ),
    ]
