# Generated by Django 2.2.5 on 2019-10-09 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0008_auto_20191009_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='date_edited',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
