# Generated by Django 3.0.5 on 2020-04-03 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0013_auto_20200328_1705'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForumConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_category', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='forum.Category')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
