# Generated by Django 3.0.5 on 2020-04-04 15:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum', '0016_auto_20200404_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='thread',
            name='locked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locker', to=settings.AUTH_USER_MODEL),
        ),
    ]
