# Generated by Django 3.0.5 on 2020-04-04 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0018_auto_20200404_1712'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='thread',
            options={'permissions': [('lock_thread', 'Can lock a thread.'), ('locked_thread_reply', 'Can reply to a locked thread.'), ('delete_other_threads', "Can delete other people's threads.")]},
        ),
    ]
