# Generated by Django 3.0.5 on 2020-04-06 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0019_auto_20200404_1728'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forumconfiguration',
            old_name='home_category',
            new_name='index_category',
        ),
    ]
