# Generated by Django 3.0.5 on 2020-04-06 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0021_auto_20200406_2132'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-y_display'], 'verbose_name_plural': 'categories'},
        ),
        migrations.RenameField(
            model_name='category',
            old_name='display_index',
            new_name='y_display',
        ),
    ]
