# Generated by Django 3.0.5 on 2020-04-06 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0022_auto_20200406_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='y_display',
            field=models.SmallIntegerField(default=-1),
        ),
    ]
