# Generated by Django 3.0.5 on 2020-04-06 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0024_auto_20200406_2136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thread',
            name='locked_by',
        ),
        migrations.AddField(
            model_name='thread',
            name='pinned',
            field=models.BooleanField(default=False),
        ),
    ]
