# Generated by Django 3.0.5 on 2020-04-07 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0025_auto_20200406_2259'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='thread',
            options={'ordering': ['-pk'], 'permissions': [('lock_thread', 'Can lock a thread.'), ('locked_thread_reply', 'Can reply to a locked thread.'), ('delete_other_threads', "Can delete other people's threads."), ('create_thread_in_staff_only', 'Can create threads in staff only categories.')]},
        ),
        migrations.AddField(
            model_name='category',
            name='staff_only',
            field=models.BooleanField(default=False),
        ),
    ]
