# Generated by Django 2.2.5 on 2019-10-10 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default=0, upload_to='images/'),
            preserve_default=False,
        ),
    ]
