# Generated by Django 2.2.5 on 2019-11-12 13:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alert_alerttype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='caused_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='caused_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='alert',
            name='thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='forum.Thread'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='type',
            field=models.CharField(choices=[('ME', 'Mention'), ('RE', 'Respond')], default='ME', max_length=2),
        ),
        migrations.DeleteModel(
            name='AlertType',
        ),
    ]
