# Generated by Django 2.2.5 on 2019-11-12 13:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20191112_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alert',
            name='seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
