# Generated by Django 2.2.5 on 2019-11-15 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_achievement_userachievement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='last_action',
        ),
        migrations.AlterField(
            model_name='achievement',
            name='criteria',
            field=models.CharField(choices=[('PC', 'Post count'), ('TC', 'Thread count'), ('UP', 'Upvotes'), ('DO', 'Downvotes')], default='PC', max_length=2),
        ),
        migrations.AlterField(
            model_name='alert',
            name='type',
            field=models.CharField(choices=[('ME', 'Mention'), ('RE', 'Respond'), ('UP', 'Upvote'), ('DO', 'Downvote'), ('AC', 'Achievement')], default='ME', max_length=2),
        ),
    ]
