# Generated by Django 3.0.5 on 2020-04-05 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Site Name', max_length=255)),
                ('description', models.TextField(default='Site Description', max_length=750)),
                ('description_short', models.TextField(default='Site Short Description', max_length=128)),
                ('keywords', models.TextField(default='keyword1, keyword2, keyword3, keyword4', max_length=750)),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='')),
            ],
            options={
                'verbose_name': 'Site configuration',
            },
        ),
        migrations.CreateModel(
            name='SiteSocialNetwork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('url', models.CharField(max_length=255)),
                ('fa_icon', models.CharField(max_length=64)),
            ],
        ),
    ]
