# Generated by Django 3.0.5 on 2020-04-06 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteColorPalette',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('special_color', models.CharField(default='2E86AB', max_length=6)),
                ('special_dark_color', models.CharField(default='065A82', max_length=6)),
            ],
            options={
                'verbose_name': 'Site color palette',
            },
        ),
    ]
