# Generated by Django 3.0.5 on 2020-04-06 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_sitecolorpalette'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitecolorpalette',
            name='background',
            field=models.CharField(default='FFFFFF', max_length=6),
        ),
        migrations.AddField(
            model_name='sitecolorpalette',
            name='background_dark',
            field=models.CharField(default='2d2d2d', max_length=6),
        ),
        migrations.AddField(
            model_name='sitecolorpalette',
            name='background_gray',
            field=models.CharField(default='E9ECEF', max_length=6),
        ),
        migrations.AddField(
            model_name='sitecolorpalette',
            name='link',
            field=models.CharField(default='007BFF', max_length=6),
        ),
        migrations.AddField(
            model_name='sitecolorpalette',
            name='link_hover',
            field=models.CharField(default='0056B3', max_length=6),
        ),
        migrations.AddField(
            model_name='sitecolorpalette',
            name='text_color',
            field=models.CharField(default='282828', max_length=6),
        ),
        migrations.AddField(
            model_name='sitecolorpalette',
            name='text_color_hover',
            field=models.CharField(default='232323', max_length=6),
        ),
        migrations.AddField(
            model_name='sitecolorpalette',
            name='text_color_light',
            field=models.CharField(default='F3EFF5', max_length=6),
        ),
        migrations.AddField(
            model_name='sitecolorpalette',
            name='text_color_light_hover',
            field=models.CharField(default='dfdbe1', max_length=6),
        ),
    ]
