# Generated by Django 3.0.5 on 2020-04-06 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_auto_20200406_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitecolorpalette',
            name='text_color_light',
            field=models.CharField(default='ffffff', max_length=6),
        ),
        migrations.AlterField(
            model_name='sitecolorpalette',
            name='text_color_light_hover',
            field=models.CharField(default='F3EFF5', max_length=6),
        ),
    ]
