# Generated by Django 3.0.5 on 2020-04-06 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0004_auto_20200406_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitecolorpalette',
            name='background_gray',
            field=models.CharField(default='F3F3F3', max_length=6),
        ),
    ]
