# Generated by Django 3.0.5 on 2020-04-03 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_sitesocial_sitesocialconfiguration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SiteSocialConfiguration',
        ),
    ]
