# Generated by Django 3.0.5 on 2020-04-03 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_delete_sitesocialconfiguration'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SiteSocial',
            new_name='SiteSocialNetwork',
        ),
    ]
