# Generated by Django 3.0.5 on 2020-04-03 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20200403_1740'),
    ]

    operations = [
        migrations.RenameField(
            model_name='siteconfiguration',
            old_name='site_name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='description',
            field=models.CharField(default='Site Description', max_length=750),
        ),
    ]
