# Generated by Django 3.0.5 on 2020-04-03 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20200403_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='description_short',
            field=models.CharField(default='Site Short Description', max_length=64),
        ),
    ]
