# Generated by Django 3.0.5 on 2020-04-03 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_siteconfiguration_description_short'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfiguration',
            name='description',
            field=models.TextField(default='Site Description', max_length=750),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='description_short',
            field=models.CharField(default='Site Short Description', max_length=128),
        ),
    ]
