# Generated by Django 3.0.5 on 2020-04-03 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_siteconfiguration_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfiguration',
            name='description_short',
            field=models.TextField(default='Site Short Description', max_length=128),
        ),
    ]
