# Generated by Django 3.0.5 on 2020-04-04 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20200403_1814'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='siteconfiguration',
            options={'verbose_name': 'Site configuration'},
        ),
    ]
