# Generated by Django 3.0.5 on 2020-04-04 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_siteconfiguration_favicon'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='keywords',
            field=models.TextField(default='keyword1, keyword2, keyword3, keyword4', max_length=750),
        ),
    ]
