# Generated by Django 3.0.5 on 2020-04-05 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_remove_siteconfiguration_maintenance_mode'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SiteConfiguration',
        ),
        migrations.DeleteModel(
            name='SiteSocialNetwork',
        ),
    ]
